version: '3.8'

services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
    app:
        container_name: api
        image: api
        build:
            context: .
            target: development
        volumes:
            - ./src:/app/src
        ports:
            - 3030:3030
        command: npm run dev
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
            PORT: 3030
        links:
            - db
        depends_on:
            - db
volumes:
    db:
        driver: local
